
const LinksImportantes = () => {
  return (
    <div className="xl:w-[1280px] m-auto flex flex-col items-center justify-center">
      <h1 className="text-4xl mb-10">Links Importantes</h1>
      <a href="" className="underline text-[#00AEED] hover:no-underline">Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempore expedita aut quae, neque eum sequi! Hic enim quam soluta esse ab quaerat possimus fugit, totam numquam temporibus cum dolorum magnam? Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum sint assumenda cupiditate harum quisquam quos ipsa facilis possimus magni necessitatibus neque dolores quaerat, distinctio voluptates, inventore excepturi ipsam et eos? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Modi dolorem, quas hic mollitia quae totam sit dolores libero illum rerum cumque voluptatem eos aperiam impedit iste culpa atque consequuntur placeat?Lorem ipsum dolor sit amet consectetur adipisicing elit. Qui corrupti fugiat, facilis quos adipisci quae dignissimos culpa tempore illum molestias enim eum optio, aperiam ab quas natus deleniti temporibus voluptate?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Veritatis amet illum numquam repellendus fuga, quae molestias similique maxime reiciendis possimus. Ex distinctio repudiandae doloremque similique accusamus autem voluptatum magnam deleniti.</a>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempore expedita aut quae, neque eum sequi! Hic enim quam soluta esse ab quaerat possimus fugit, totam numquam temporibus cum dolorum magnam? Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum sint assumenda cupiditate harum quisquam quos ipsa facilis possimus magni necessitatibus neque dolores quaerat, distinctio voluptates, inventore excepturi ipsam et eos? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Modi dolorem, quas hic mollitia quae totam sit dolores libero illum rerum cumque voluptatem eos aperiam impedit iste culpa atque consequuntur placeat?Lorem ipsum dolor sit amet consectetur adipisicing elit. Qui corrupti fugiat, facilis quos adipisci quae dignissimos culpa tempore illum molestias enim eum optio, aperiam ab quas natus deleniti temporibus voluptate?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Veritatis amet illum numquam repellendus fuga, quae molestias similique maxime reiciendis possimus. Ex distinctio repudiandae doloremque similique accusamus autem voluptatum magnam deleniti.</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempore expedita aut quae, neque eum sequi! Hic enim quam soluta esse ab quaerat possimus fugit, totam numquam temporibus cum dolorum magnam? Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum sint assumenda cupiditate harum quisquam quos ipsa facilis possimus magni necessitatibus neque dolores quaerat, distinctio voluptates, inventore excepturi ipsam et eos? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Modi dolorem, quas hic mollitia quae totam sit dolores libero illum rerum cumque voluptatem eos aperiam impedit iste culpa atque consequuntur placeat?Lorem ipsum dolor sit amet consectetur adipisicing elit. Qui corrupti fugiat, facilis quos adipisci quae dignissimos culpa tempore illum molestias enim eum optio, aperiam ab quas natus deleniti temporibus voluptate?Lorem ipsum, dolor sit amet consectetur adipisicing elit. Veritatis amet illum numquam repellendus fuga, quae molestias similique maxime reiciendis possimus. Ex distinctio repudiandae doloremque similique accusamus autem voluptatum magnam deleniti.</p>
    </div>
  )
}

export default LinksImportantes