export const candidatos = [
  { nome: 'Thiago Rosa', cpf: '119.xxx.xxx-00' },
  { nome: 'Juciara Carvalho ', cpf: '106.xxx.xxx-05' },
  { nome: 'Cristiane Marx', cpf: '058.xxx.xxx-27' },
  { nome: 'Gessika Ferreira', cpf: '094.xxx.xxx-00' },
  { nome: 'Anderson Lucas', cpf: '258.xxx.xxx-94' },
  { nome: 'Lorrana de Oliveira', cpf: '369.xxx.xxx-07' },
  { nome: 'Ana Paula Cardozo', cpf: '313.xxx.xxx-80' },
  { nome: 'Gian Stupp', cpf: '108.xxx.xxx-00' },
  { nome: 'Catiana Forster', cpf: '038.xxx.xxx-50' },
  { nome: 'João Masnik', cpf: '816.xxx.xxx-91' },
  { nome: 'Gerson Rovatti', cpf: '019.xxx.xxx-67' },
  { nome: 'Elivelton Casanova', cpf: '083.xxx.xxx-40' },
  { nome: 'Patricia da Silva', cpf: '056.xxx.xxx-33' },
  { nome: 'Luiz Antonio de Sá', cpf: '594.xxx.xxx-53' },
  { nome: 'Douglas de Barros', cpf: '040.xxx.xxx-66' },
  { nome: 'Tanabí Mozel', cpf: '052.xxx.xxx-57' },
  { nome: 'Hortencia Santana ', cpf: '154.xxx.xxx-26' },
  { nome: 'Claudia Pezzi', cpf: '833.xxx.xxx-04 ' },
  { nome: 'Rodrigo Gomes', cpf: '081.xxx.xxx-56' },
  { nome: 'Thiago Pereira', cpf: '029.xxx.xxx-10' },
  { nome: 'Mirlene Dias', cpf: '040.xxx.xxx-40' },
  { nome: 'Juliane Sperandio', cpf: '049.xxx.xxx-46' },
  { nome: 'Andressa Schipanski', cpf: '094.xxx.xxx-40' },
  { nome: 'Fabíola Walter', cpf: '052.xxx.xxx-63' },
  { nome: 'Cristiane dos Santos', cpf: '079.xxx.xxx-89' }
]
