export const candidatos2025 = [
  { nome: 'Luanna Santos', cpf: '9xxxxx68' },
  { nome: 'Bruna Mendes ', cpf: '0xxxxx70' },
  { nome: 'Victor Cavalcante', cpf: '0xxxxx40' },
  { nome: 'Benedito Neto', cpf: '0xxxxx18' },
  { nome: 'Priscila Tempone', cpf: '6xxxxx91' },
  { nome: 'María Angélica Matias', cpf: '7xxxxx12' },
  { nome: 'Francilene Silva', cpf: '0xxxxx06' },
  { nome: 'Renilson Custódio', cpf: '8xxxxx34' },
  { nome: 'Renato Junior', cpf: '1xxxxx71' },
  { nome: 'Aline Santos', cpf: '1xxxxx10' },
  { nome: 'Jose Neto', cpf: '3xxxxx82' },
  { nome: 'Jessica Canuto', cpf: '0xxxxx44' },
  { nome: 'Helen Pereira', cpf: '7xxxxx15' },
  { nome: 'Mirian de Andrade', cpf: '0xxxxx26' },
  { nome: 'Moisés Moniz', cpf: '0xxxxx40' },
  { nome: 'Marcos Pinto', cpf: '9xxxxx15' },
  { nome: 'Ildenice Costa', cpf: '6xxxxx53' },
  { nome: 'Douglas Fontes', cpf: '0xxxxx07 ' },
  { nome: 'João Pereira', cpf: '0xxxxx83' },
  { nome: 'Marina Camilo', cpf: '0xxxxx03' },
  { nome: 'Amaral Gomes', cpf: '6xxxxx00' },
  { nome: 'Thais Freitas', cpf: '0xxxxx06' },
  { nome: 'Olga de Menezes', cpf: '6xxxxx04' },
  { nome: 'Brigite Marcos', cpf: '8xxxxx00' },
  { nome: 'Eduarda Moura', cpf: '7xxxxx23' },
  { nome: 'Lanna Gonçalves', cpf: '0xxxxx80' },
  { nome: 'Jose Junior', cpf: '0xxxxx82' },
  { nome: 'Maria Gonçalves', cpf: '0xxxxx05' },
  { nome: 'Luana Lucianete', cpf: '6xxxxx87' }
]
