export const classificadosAr = [
  { nome: 'Agustina Moreta', cpf: '4xxxxx28' },
  { nome: 'Camila Campitelli', cpf: '3xxxxx34' },
  { nome: 'Cecilia Penessi', cpf: '3xxxxx88' },
  { nome: 'Eliana Mavero', cpf: '3xxxxx64' },
  { nome: 'Emanuel Andino', cpf: '3xxxxx73' },
  { nome: 'Graciela Demti', cpf: '1xxxxx90' },
  { nome: 'Jose Tosco', cpf: '2xxxxx06' },
  { nome: 'Lara Vidal', cpf: '4xxxxx66' },
  { nome: 'Laura Silvestri', cpf: '2xxxxx36' },
  { nome: 'Marcela Mandolini', cpf: '2xxxxx31' },
  { nome: 'María Vital', cpf: '2xxxxx19' },
  { nome: 'Mariana Peroni', cpf: '2xxxxx74' },
  { nome: 'Marlene Bozza', cpf: '2xxxxx81' },
  { nome: 'Martin Pagliaro', cpf: '2xxxxx93' },
  { nome: 'Pilar Yujnovsky', cpf: '4xxxxx08' },
  { nome: 'Stefanela Ferraro', cpf: '4xxxxx77' },
  { nome: 'Vanesa Medina', cpf: '3xxxxx04' },
  { nome: 'Verónica Mellado', cpf: '3xxxxx45' }
]
